### ISSUE TITLE
Implement Levenshtein distance

### ISSUE THREAD

**Issue by peter279k** [DivineOmega/php-distance#5]
@DivineOmega .The distance has been already available in [native PHP function](http://www.php.net/levenshtein).

Do you integrate this function to in this package ?

**Comment by Jord-JD** [comment]
I'm not sure. 

Levenshtein distance is a measurement for string distance. This library was intended to provide calculation of physical, real world distance measurements.

**Comment by peter279k** [comment]
It's the string distance, and it's not related to this repo purpose.

It's closed.
